[versions]
agp = "8.1.4"
appcompat = "1.6.1"
annotation = "1.7.0"
cardview = "1.0.0"
compile_sdk_version = "34"
constraintlayout = "2.1.4"
core_ktx = "1.12.0"
detekt = "1.23.3"
junit = "4.13.2"
kotlin = "1.9.21"
ktlint_gradle = "11.6.1"
min_sdk_version = "14"
mockito_core = "5.7.0"
recyclerview = "1.3.2"
viewpager2 = "1.1.0-beta02"
target_sdk_version = "34"
fragment = "1.6.2"

[libraries]
androidx_annotation = { module = "androidx.annotation:annotation", version.ref = "annotation" }
androidx_appcompat = { module = "androidx.appcompat:appcompat", version.ref = "appcompat" }
androidx_cardview = { module = "androidx.cardview:cardview", version.ref = "cardview" }
androidx_constraintlayout = { module = "androidx.constraintlayout:constraintlayout", version.ref = "constraintlayout" }
androidx_core_ktx = { module = "androidx.core:core-ktx", version.ref = "core.ktx" }
androidx_recyclerview = { module = "androidx.recyclerview:recyclerview", version.ref = "recyclerview" }
androidx_viewpager2 = { module = "androidx.viewpager2:viewpager2", version.ref = "viewpager2"}
androidx_fragment = { module = "androidx.fragment:fragment-ktx", version.ref = "fragment"}
junit = { module = "junit:junit", version.ref = "junit" }
mockito_core = { module = "org.mockito:mockito-core", version.ref = "mockito.core" }

[plugins]
application = { id = "com.android.application", version.ref = "agp" }
kotlin_android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
library = { id = "com.android.library", version.ref = "agp" }
detekt = { id = "io.gitlab.arturbosch.detekt", version.ref = "detekt" }
ktlint = { id = "org.jlleitschuh.gradle.ktlint", version.ref = "ktlint.gradle" }